### PR TITLE
Add memory information

### PR DESCRIPTION
**Pull request by teamclouday**
Hi, your profiler is very useful to analyze pytorch models layer by layer, but it only contains runtime information. So I update your code to also include memory allocation information.

### CODE REVIEW

**Comment by awwong1** [comment]
Thanks! Just taking a look at it now.
Do you happen to know what the minimum PyTorch version is that supports the `profile_memory` argument?
Before I merge this in, I would like to also support older versions.

**Comment by teamclouday** [comment]
I just searched for it. Looks like v1.6.0. The release note is [here](https://github.com/pytorch/pytorch/releases/tag/v1.6.0)

**Comment by awwong1** [comment]
Feature has been added, new version `1.3.0` has been pushed.
Please let me know if this is satisfactory for your use case and if you encounter any issues, @teamclouday!

**Comment by teamclouday** [comment]
Thanks! I looked at it and it looks great!

**Comment by teamclouday** [comment]
Just one more problem about memory information. According to [this document](https://pytorch.org/tutorials/recipes/recipes/profiler.html#use-profiler-to-analyze-memory-consumption),  ‘self’ memory corresponds to the memory allocated (released) by the operator, excluding the children calls to the other operators.   
So I assume `self_cpu_memory_usage` <= `cpu_memory_usage`, but when I was testing your profiler, `self_cpu_memory_usage` is always larger than `cpu_memory_usage`.  
Is it because you define [`Measure`](https://github.com/awwong1/torchprof/blob/master/torchprof/display.py#L5) in "cpu_memory", "self_cpu_memory" order, but later define in [`heading`](https://github.com/awwong1/torchprof/blob/master/torchprof/display.py#L201) in a reverse order?

**Comment by awwong1** [comment]
> Is it because you define [`Measure`](https://github.com/awwong1/torchprof/blob/master/torchprof/display.py#L5) in "cpu_memory", "self_cpu_memory" order, but later define in [`heading`](https://github.com/awwong1/torchprof/blob/master/torchprof/display.py#L201) in a reverse order?

It's unlikely the order of the Measure named tuple this is the cause of the issue, because all of my calls use keyword arguments (order doesn't matter).
I'm looking into what the expected logic should be for a 'layer' level view of the model. 
Currently, I sum all of the function events- this may be incorrect behavior. 

Do you see any invalid behavior with `show_events=True`?

**Comment by teamclouday** [comment]
In fact, I tested the original pytorch profiler on the same model for comparison:  
```python3
with torch.autograd.profiler.profile(profile_memory=True, use_cuda=True) as prof2:
    cnn(inputData0)
print(prof2.table())
```
which yields:  
```
--------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                            Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls  
--------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                    aten::conv2d         0.15%       8.500us         2.74%     152.000us     152.000us       2.592us         0.01%      47.488us      47.488us           0 b           0 b     256.00 Kb           0 b             1  
               aten::convolution         0.10%       5.500us         2.58%     143.500us     143.500us       3.936us         0.01%      44.896us      44.896us           0 b           0 b     256.00 Kb           0 b             1  
              aten::_convolution         0.33%      18.600us         2.48%     138.000us     138.000us       5.920us         0.02%      40.960us      40.960us           0 b           0 b     256.00 Kb           0 b             1  
                aten::contiguous         0.05%       2.800us         0.05%       2.800us       2.800us       2.016us         0.01%       2.016us       2.016us           0 b           0 b           0 b           0 b             1  
         aten::cudnn_convolution         1.71%      94.800us         2.10%     116.600us     116.600us      29.088us         0.09%      33.024us      33.024us           0 b           0 b     256.00 Kb      -6.50 Kb             1  
                     aten::empty         0.17%       9.700us         0.17%       9.700us       9.700us       0.000us         0.00%       0.000us       0.000us           0 b           0 b     256.00 Kb     256.00 Kb             1  
                aten::contiguous         0.04%       2.400us         0.04%       2.400us       2.400us       2.048us         0.01%       2.048us       2.048us           0 b           0 b           0 b           0 b             1  
                   aten::resize_         0.03%       1.900us         0.03%       1.900us       1.900us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                aten::contiguous         0.03%       1.900us         0.03%       1.900us       1.900us       1.888us         0.01%       1.888us       1.888us           0 b           0 b           0 b           0 b             1  
                   aten::resize_         0.01%       0.300us         0.01%       0.300us       0.300us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                    aten::stride         0.01%       0.500us         0.01%       0.500us       0.500us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                    aten::stride         0.00%       0.200us         0.00%       0.200us       0.200us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                    aten::stride         0.00%       0.200us         0.00%       0.200us       0.200us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                    aten::stride         0.01%       0.300us         0.01%       0.300us       0.300us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                     aten::empty         0.08%       4.400us         0.08%       4.400us       4.400us       0.000us         0.00%       0.000us       0.000us           0 b           0 b       6.50 Kb       6.50 Kb             1  
                       aten::add         0.41%      22.700us         0.49%      27.000us      27.000us       9.952us         0.03%       9.952us       9.952us           0 b           0 b         512 b           0 b             1  
                     aten::empty         0.08%       4.300us         0.08%       4.300us       4.300us       0.000us         0.00%       0.000us       0.000us           0 b           0 b         512 b         512 b             1  
                aten::batch_norm         0.12%       6.400us         1.87%     103.600us     103.600us       4.032us         0.01%      42.080us      42.080us           0 b           0 b     257.00 Kb           0 b             1  
    aten::_batch_norm_impl_index         0.30%      16.500us         1.75%      97.200us      97.200us      13.408us         0.04%      38.048us      38.048us           0 b           0 b     257.00 Kb           0 b             1  
                aten::contiguous         0.04%       2.100us         0.04%       2.100us       2.100us       2.048us         0.01%       2.048us       2.048us           0 b           0 b           0 b           0 b             1  
                aten::contiguous         0.03%       1.800us         0.03%       1.800us       1.800us       1.696us         0.00%       1.696us       1.696us           0 b           0 b           0 b           0 b             1  
                aten::contiguous         0.03%       1.800us         0.03%       1.800us       1.800us       0.704us         0.00%       0.704us       0.704us           0 b           0 b           0 b           0 b             1  
                aten::contiguous         0.03%       1.700us         0.03%       1.700us       1.700us       2.048us         0.01%       2.048us       2.048us           0 b           0 b           0 b           0 b             1  
                aten::contiguous         0.03%       1.700us         0.03%       1.700us       1.700us       1.824us         0.01%       1.824us       1.824us           0 b           0 b           0 b           0 b             1  
          aten::cudnn_batch_norm         0.87%      48.200us         1.29%      71.600us      71.600us      16.320us         0.05%      16.320us      16.320us           0 b           0 b     257.00 Kb           0 b             1  
                aten::empty_like         0.05%       2.600us         0.19%      10.300us      10.300us       0.000us         0.00%       0.000us       0.000us           0 b           0 b     256.00 Kb           0 b             1  
                     aten::empty         0.14%       7.700us         0.14%       7.700us       7.700us       0.000us         0.00%       0.000us       0.000us           0 b           0 b     256.00 Kb     256.00 Kb             1  
                      aten::view         0.08%       4.300us         0.08%       4.300us       4.300us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                     aten::empty         0.06%       3.500us         0.06%       3.500us       3.500us       0.000us         0.00%       0.000us       0.000us           0 b           0 b         512 b         512 b             1  
                     aten::empty         0.06%       3.400us         0.06%       3.400us       3.400us       0.000us         0.00%       0.000us       0.000us           0 b           0 b         512 b         512 b             1  
                     aten::empty         0.02%       1.000us         0.02%       1.000us       1.000us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                     aten::empty         0.02%       0.900us         0.02%       0.900us       0.900us       0.000us         0.00%       0.000us       0.000us           0 b           0 b           0 b           0 b             1  
                      aten::relu         0.27%      15.000us         7.67%     426.200us     426.200us       8.192us         0.02%      14.336us      14.336us           0 b           0 b     256.00 Kb           0 b             1  
                 aten::threshold         0.28%      15.500us         7.40%     411.200us     411.200us       6.144us         0.02%       6.144us       6.144us           0 b           0 b     256.00 Kb           0 b             1  
                     aten::empty         7.12%     395.700us         7.12%     395.700us     395.700us       0.000us         0.00%       0.000us       0.000us           0 b           0 b     256.00 Kb     256.00 Kb             1  
                    aten::conv2d         0.08%       4.600us         1.54%      85.500us      85.500us       2.624us         0.01%     100.480us     100.480us           0 b           0 b     256.00 Kb           0 b             1 
```
By using your profiler:  
```python3
with torchprof.Profile(cnn, profile_memory=True, use_cuda=True) as prof:
    cnn(inputData0)
print(prof.display(show_events=True))
```
It shows:  
```
Module                               | Self CPU total | CPU total | Self CUDA total | CUDA total | Self CPU Mem | CPU Mem | Self CUDA Mem | CUDA Mem  | Number of Calls
-------------------------------------|----------------|-----------|-----------------|------------|--------------|---------|---------------|-----------|----------------
ResNet                               |                |           |                 |            |              |         |               |           |                
├── conv1                            |                |           |                 |            |              |         |               |           |                
│├── aten::conv2d                    | 8.400us        | 161.900us | 3.808us         | 445.056us  | 0 b          | 0 b     | 256.00 Kb     | 0 b       | 1              
│├── aten::convolution               | 6.400us        | 153.500us | 3.552us         | 441.248us  | 0 b          | 0 b     | 256.00 Kb     | 0 b       | 1              
│├── aten::_convolution              | 18.300us       | 147.100us | 5.984us         | 437.696us  | 0 b          | 0 b     | 256.00 Kb     | 0 b       | 1              
│├── aten::contiguous                | 6.600us        | 6.600us   | 5.312us         | 5.312us    | 0 b          | 0 b     | 0 b           | 0 b       | 3              
│├── aten::cudnn_convolution         | 101.800us      | 126.000us | 426.400us       | 429.920us  | 0 b          | 0 b     | 256.00 Kb     | -6.50 Kb  | 1              
│├── aten::empty                     | 17.200us       | 17.200us  | 0.000us         | 0.000us    | 0 b          | 0 b     | 262.50 Kb     | 262.50 Kb | 2              
│├── aten::resize_                   | 2.100us        | 2.100us   | 0.000us         | 0.000us    | 0 b          | 0 b     | 0 b           | 0 b       | 2              
│└── aten::stride                    | 1.100us        | 1.100us   | 0.000us         | 0.000us    | 0 b          | 0 b     | 0 b           | 0 b       | 4              
├── bn1                              |                |           |                 |            |              |         |               |           |                
│├── aten::add                       | 24.000us       | 29.000us  | 8.608us         | 8.608us    | 0 b          | 0 b     | 512 b         | 0 b       | 1              
│├── aten::empty                     | 18.200us       | 18.200us  | 0.000us         | 0.000us    | 0 b          | 0 b     | 257.50 Kb     | 257.50 Kb | 6              
│├── aten::batch_norm                | 6.400us        | 100.800us | 3.520us         | 40.544us   | 0 b          | 0 b     | 257.00 Kb     | 0 b       | 1              
│├── aten::_batch_norm_impl_index    | 15.800us       | 94.400us  | 12.288us        | 37.024us   | 0 b          | 0 b     | 257.00 Kb     | 0 b       | 1              
│├── aten::contiguous                | 9.100us        | 9.100us   | 8.448us         | 8.448us    | 0 b          | 0 b     | 0 b           | 0 b       | 5              
│├── aten::cudnn_batch_norm          | 49.800us       | 69.500us  | 16.288us        | 16.288us   | 0 b          | 0 b     | 257.00 Kb     | 0 b       | 1              
│├── aten::empty_like                | 2.600us        | 7.300us   | 0.000us         | 0.000us    | 0 b          | 0 b     | 256.00 Kb     | 0 b       | 1              
│└── aten::view                      | 3.900us        | 3.900us   | 0.000us         | 0.000us    | 0 b          | 0 b     | 0 b           | 0 b       | 1              
├── layer1                           |                |           |                 |            |              |         |               |           |                
│├── 0                               |                |           |                 |            |              |         |               |           |                
││├── conv1                          |                |           |                 |            |              |         |               |           |                
│││├── aten::conv2d                  | 4.500us        | 86.900us  | 2.656us         | 100.544us  | 0 b          | 0 b     | 256.00 Kb     | 0 b       | 1                    
```
The memory part looks flipped for me.  
Also, I observe that some functions such as `aten::relu` and `aten::threshold` are omitted in the output. Is this expected behavior?

**Comment by awwong1** [comment]
I updated the library such that the memory columns are no longer flipped.
As for the functions being omitted in the output, this is not expected behavior.
Can you share your full resnet model?

When I test my profiler using `torchvision.models.resnet.resnet18(pretrained=False)` I can see the relu and maxpool layers, but I notice your profiler output does not show them.

```python
model = torchvision.models.resnet.resnet18(pretrained=False)                                                                                                                                                                                                               
with torchprof.Profile(model, use_cuda=True, profile_memory=True) as prof:
    model(x)
print(prof.display(show_events=True))
```
```text
Module                               | Self CPU total | CPU total | Self CUDA total | CUDA total | Self CPU Mem | CPU Mem   | Self CUDA Mem | CUDA Mem | Number of Calls
-------------------------------------|----------------|-----------|-----------------|------------|--------------|-----------|---------------|----------|----------------
ResNet                               |                |           |                 |            |              |           |               |          |                
├── conv1                            |                |           |                 |            |              |           |               |          |                
│├── aten::conv2d                    | 11.381us       | 3.013ms   | 11.264us        | 3.013ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::convolution               | 9.909us        | 3.002ms   | 9.760us         | 3.002ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::_convolution              | 31.319us       | 2.992ms   | 31.424us        | 2.992ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::contiguous                | 5.440us        | 5.440us   | 5.312us         | 5.312us    | 0 b          | 0 b       | 0 b           | 0 b      | 2              
│├── aten::mkldnn_convolution        | 2.932ms        | 2.955ms   | 2.949ms         | 2.955ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::empty                     | 15.490us       | 15.490us  | 0.000us         | 0.000us    | 3.06 Mb      | 3.06 Mb   | 0 b           | 0 b      | 1              
│└── aten::as_strided_               | 8.326us        | 8.326us   | 6.016us         | 6.016us    | 0 b          | 0 b       | 0 b           | 0 b      | 1              
├── bn1                              |                |           |                 |            |              |           |               |          |                
│├── aten::add                       | 25.288us       | 29.125us  | 29.088us        | 29.088us   | 0 b          | 8 b       | 0 b           | 0 b      | 1              
│├── aten::empty                     | 27.572us       | 27.572us  | 0.000us         | 0.000us    | 3.06 Mb      | 3.06 Mb   | 0 b           | 0 b      | 5              
│├── aten::batch_norm                | 10.630us       | 1.270ms   | 10.144us        | 1.269ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::_batch_norm_impl_index    | 10.350us       | 1.259ms   | 12.768us        | 1.259ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::native_batch_norm         | 1.060ms        | 1.246ms   | 1.098ms         | 1.246ms    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│├── aten::select                    | 131.254us      | 152.584us | 148.096us       | 148.096us  | 0 b          | 0 b       | 0 b           | 0 b      | 24             
│├── aten::as_strided                | 21.330us       | 21.330us  | 0.000us         | 0.000us    | 0 b          | 0 b       | 0 b           | 0 b      | 24             
│├── aten::empty_like                | 3.877us        | 18.124us  | 0.000us         | 0.000us    | 0 b          | 3.06 Mb   | 0 b           | 0 b      | 1              
│└── aten::stride                    | 9.306us        | 9.306us   | 0.000us         | 0.000us    | 0 b          | 0 b       | 0 b           | 0 b      | 16             
├── relu                             |                |           |                 |            |              |           |               |          |                
│├── aten::relu_                     | 20.939us       | 133.551us | 20.320us        | 133.600us  | 0 b          | 0 b       | 0 b           | 0 b      | 1              
│└── aten::threshold_                | 112.612us      | 112.612us | 113.280us       | 113.280us  | 0 b          | 0 b       | 0 b           | 0 b      | 1              
├── maxpool                          |                |           |                 |            |              |           |               |          |                
│├── aten::max_pool2d                | 9.668us        | 5.313ms   | 9.568us         | 5.313ms    | 0 b          | 2.30 Mb   | 0 b           | 0 b      | 1              
│├── aten::max_pool2d_with_indices   | 5.284ms        | 5.303ms   | 5.300ms         | 5.303ms    | 0 b          | 2.30 Mb   | 0 b           | 0 b      | 1              
│├── aten::empty                     | 4.178us        | 4.178us   | 0.000us         | 0.000us    | 0 b          | 0 b       | 0 b           | 0 b      | 2              
│├── aten::contiguous                | 3.727us        | 3.727us   | 3.296us         | 3.296us    | 0 b          | 0 b       | 0 b           | 0 b      | 1              
│└── aten::resize_                   | 10.811us       | 10.811us  | 0.000us         | 0.000us    | 2.30 Mb      | 2.30 Mb   | 0 b           | 0 b      | 2              
├── layer1                           |                |           |                 |            |              |           |               |          |                
│├── 0                               |                |           |                 |            |              |           |               |          |                
││├── conv1                          |                |           |                 |            |              |           |               |          |                
│││├── aten::conv2d                  | 8.706us        | 2.201ms   | 8.800us         | 2.201ms    | 0 b          | 784.00 Kb | 0 b           | 0 b      | 1              
...
```

**Comment by teamclouday** [comment]
Thanks!  
I'll paste my resnet model here:  
```python3
'''ResNet18/34/50/101/152 in Pytorch.'''
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.autograd import Variable


def conv3x3(in_planes, out_planes, stride=1):
    return nn.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride, padding=1, bias=False)


class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_planes, planes, stride=1):
        super(BasicBlock, self).__init__()
        self.conv1 = conv3x3(in_planes, planes, stride)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = nn.BatchNorm2d(planes)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != self.expansion*planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, self.expansion*planes, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(self.expansion*planes)
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        out = F.relu(out)
        return out


class Bottleneck(nn.Module):
    expansion = 4

    def __init__(self, in_planes, planes, stride=1):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, self.expansion*planes, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(self.expansion*planes)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != self.expansion*planes:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, self.expansion*planes, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(self.expansion*planes)
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = F.relu(self.bn2(self.conv2(out)))
        out = self.bn3(self.conv3(out))
        out += self.shortcut(x)
        out = F.relu(out)
        return out


class ResNet(nn.Module):
    def __init__(self, block, num_blocks, num_classes=10):
        super(ResNet, self).__init__()
        self.in_planes = 64

        self.conv1 = conv3x3(3,64)
        self.bn1 = nn.BatchNorm2d(64)
        self.layer1 = self._make_layer(block, 64, num_blocks[0], stride=1)
        self.layer2 = self._make_layer(block, 128, num_blocks[1], stride=2)
        self.layer3 = self._make_layer(block, 256, num_blocks[2], stride=2)
        self.layer4 = self._make_layer(block, 512, num_blocks[3], stride=2)
        self.linear = nn.Linear(512*block.expansion, num_classes)

    def _make_layer(self, block, planes, num_blocks, stride):
        strides = [stride] + [1]*(num_blocks-1)
        layers = []
        for stride in strides:
            layers.append(block(self.in_planes, planes, stride))
            self.in_planes = planes * block.expansion
        return nn.Sequential(*layers)

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.layer4(out)
        out = F.avg_pool2d(out, 4)
        out = out.view(out.size(0), -1)
        out = self.linear(out)
        return out

    def get_embedding(self, x, k):
        if k == 1:
            x = self.layer1(F.relu(self.bn1(self.conv1(x))))
        if k == 2:
            x = self.layer2(self.layer1(F.relu(self.bn1(self.conv1(x)))))
        if k == 3:
            x = self.layer3(self.layer2(self.layer1(F.relu(self.bn1(self.conv1(x))))))
        if k == 4:
            x = self.layer4(self.layer3(self.layer2(self.layer1(F.relu(self.bn1(self.conv1(x)))))))
        return x


def ResNet18(num_classes=10):
    return ResNet(BasicBlock, [2,2,2,2], num_classes)

def ResNet34(num_classes=10):
    return ResNet(BasicBlock, [3,4,6,3], num_classes)

def ResNet50(num_classes=10):
    return ResNet(Bottleneck, [3,4,6,3], num_classes)

def ResNet101(num_classes=10):
    return ResNet(Bottleneck, [3,4,23,3], num_classes)

def ResNet152(num_classes=10):
    return ResNet(Bottleneck, [3,8,36,3], num_classes)

def test_resnet():
    net = ResNet50()
    y = net(Variable(torch.randn(1,3,32,32)))
    print(y.size())

# test_resnet()
```
The model I'm using is Resnet18. Comparing with Pytorch torchvision resnet model [here](https://github.com/pytorch/pytorch/blob/master/benchmarks/functional_autograd_benchmark/torchvision_models.py#L114), seems that my version is using the `relu` function instead of the layer one. Is this the reason why it is not captured in the profiler?  
If so, I can try to use `nn.ReLU` instead.

**Pull request merged**
